# Generated by Django 2.1.4 on 2019-02-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190228_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='main/photos', verbose_name='Фото'),
        ),
    ]
