# Generated by Django 2.1.4 on 2019-03-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190302_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='born',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='news',
            name='verificated',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', verbose_name='Рейтинг'),
        ),
    ]
