# Generated by Django 2.1.4 on 2019-03-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190302_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='born',
        ),
        migrations.RemoveField(
            model_name='news',
            name='verificated',
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Заголовок Новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
